#!/usr/bin/env bash
set -eux

$(npm bin)/rimraf dist

MDXs=$(ls src/*.mdx | xargs -I'{}' basename {} .mdx)

echo $MDXs | xargs -I'{}' -n1 $(npm bin)/mdx-deck build src/{}.mdx --no-html --out-dir ./dist/{}
echo $MDXs | xargs -I'{}' -n1 $(npm bin)/mdx-deck pdf src/{}.mdx --out-file {}.pdf

cp -R ./src/assets ./dist/assets
